<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Chat.aspx.cs" Inherits="WebApplication1.Chat" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }

        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
            height: 326px;
        }
    </style>


    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.10.2.js"></script>
    <script src="Scripts/jquery.signalR-2.0.0.js"></script>

    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>

    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub.
            var chat = $.connection.chatHub;

            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message.
                var encodedName = $('<p />').text(name).html();
                var encodedMsg = $('<p />').text(message).html();
                // Add the message to the page.
                $('#divChat').append('<strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '<br />');
            };


            // Create a function that the hub can call to broadcast messages.
            chat.client.addClientToChat = function (name) {
                // Html encode display name and message.
                var encodedName = '<li >' + name + '</li>';
                
                // Add the new user to the list of users
                $('#listOnlineUsers').append(encodedName);
            };


            //// Get the user name and store it to prepend to messages.
            //$('#displayname').val(prompt('Enter your name:', ''));

            $('#btnLogin').click(function ()
            {
                $('#displayname').val($("#txtUser").val());
                // Call the Send method on the hub.
                chat.server.clientLogin($('#displayname').val());
                $("#btnLogin").attr('disabled', 'disabled');
            });



            $('#ClientLogout').click(function () {
                // Call the Send method on the hub.
                chat.server.clientLogout($('#displayname').val());                
                $('#btnLogin').removeAttr('disabled');
            });

            

            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#btnSend').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(), $('#txtMessage').val());
                    // Clear text box and reset focus for next comment.
                    $('#txtMessage').val('').focus();
                });
            });
        });
    </script>





</head>
<body>

    <div>

        <input type="hidden" id="displayname" />

        <table class="auto-style1">
            <tr>
                <td colspan="2">
                    
                    <form>
                    Enter UserName:&nbsp;
                    <input id="txtUser" type="text" />
                
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp; 
                    <input id="btnLogin" value="Login" type="button" />
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <input id="btnLogout" value="Logout" type="button" />
                    </form>
                </td>
            </tr>
            <tr>
                <td>
                    Online users:
                    <div class="container">
                        <ul id="listOnlineUsers" style="height: 309px; margin-top: 0px; width: 210px; background-color: silver;">
                        </ul>
                    </div>
                </td>
                <td>                    
                    <div class="container">
                        <div id="divChat" style="height: 309px; width: 419px;" />
                    </div>

                </td>
            </tr>
            <tr>                
                <td colspan="2">
                    <form>
                        <input type="text" id="txtMessage" style="width: 1067px" />
                        &nbsp;&nbsp;&nbsp;&nbsp;                    
                        <input id="btnSend" value="Send" style="height: 23px" type="button" />
                    </form>
                </td>
                <td colspan="2">&nbsp;</td>
            </tr>
        </table>

    </div>

</body>
</html>
