<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Chat.aspx.cs" Inherits="WebApplication1.Chat" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }

        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
            height: 326px;
        }
    </style>


    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.10.2.js"></script>
    <script src="Scripts/jquery.signalR-2.0.0.js"></script>

    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>

    <!--Add script to update the page and send messages.-->
    <script src="Scripts/chatScript.js"></script>




</head>
<body>

    <div>

        <input type="hidden" id="displayname" />

        <table class="auto-style1">
            <tr>
                <td colspan="2">
                    
                    <form>
                    Enter UserName:&nbsp;
                    <input id="txtUser" type="text" />
                
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp; 
                    <input id="btnLogin" value="Login" type="button" />
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <input id="btnLogout" value="Logout" type="button" />
                    </form>
                </td>
            </tr>
            <tr>
                <td>
                    Online users:
                    <div class="container">
                        <ul id="listOnlineUsers" style="height: 309px; margin-top: 0px; width: 210px; background-color: silver;">
                        </ul>
                    </div>
                </td>
                <td>                    
                    <div class="container">
                        <div id="divChat" style="height: 309px; width: 419px;" />
                    </div>

                </td>
            </tr>
            <tr>                
                <td colspan="2">
                    <form>
                        <input type="text" id="txtMessage" style="width: 1067px" />
                        &nbsp;&nbsp;&nbsp;&nbsp;                    
                        <input id="btnSend" value="Send" style="height: 23px" type="button" />
                    </form>
                </td>
                <td colspan="2">&nbsp;</td>
            </tr>
        </table>

    </div>
    <input type="hidden" id="hdnPrivateChatUser" />

</body>
</html>
